-- Migration 005: Add metadata fields to bot table
-- Adds description, goal, and outputFiles fields for better bot documentation

ALTER TABLE bots ADD COLUMN goal TEXT NULL;
ALTER TABLE bots ADD COLUMN "outputFiles" TEXT NULL;

-- Create index for faster queries
CREATE INDEX idx_bots_active ON bots(is_active, project_id);

-- Add column comment for clarity
COMMENT ON COLUMN bots.goal IS 'Goal of the bot - what the student receives on exit';
COMMENT ON COLUMN bots."outputFiles" IS 'JSON array of output file types generated by this bot';
